require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'config/environments/*'
    - 'config/initializers/devise.rb'
    - 'spec/**/*_spec.rb'
    - 'bin/bundle'
    - 'db/schema.rb'
    - 'node_modules/node-sass/src/libsass/extconf.rb'
    - 'node_modules/node-sass/src/libsass/contrib/libsass.spec'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    